CREATE OR REPLACE FORCE VIEW ODS.VW_AML_ACAM_CERTIFICATION(AML_ACAM_CERTFN_KEY, ACAM_ID, CERTFN_TITL, CERTFN_TYPE, COST, STRT_DT, END_DT, PMT_DT, CMMTS, CERTFN_NM, EMPL_STAT, CEU_REQ_CNT, CREATR, CREATN_DT, MODFR, CHG_DT, VRSN, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "AML_ACAM_CERTFN_KEY","ACAM_ID","CERTFN_TITL","CERTFN_TYPE","COST","STRT_DT","END_DT","PMT_DT","CMMTS","CERTFN_NM","EMPL_STAT","CEU_REQ_CNT","CREATR","CREATN_DT","MODFR","CHG_DT","VRSN","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM AML_ACAM_Certification
/



CREATE OR REPLACE FORCE VIEW ODS.VW_AML_BLACKLIST_COUNTRY(AML_BLKLIST_CRTY_KEY, BLKLIST_CRTY_ID, CRTY, ORG, LIST_ADD_DT, RMVL_DT, SPRTG_DOCN_LINK, STAT, CREATR, MODFR, CREATN_DT, CHG_DT, VRSN, ATTCHMT_FLG, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID, CMMTS) AS 
select "AML_BLKLIST_CRTY_KEY","BLKLIST_CRTY_ID","CRTY","ORG","LIST_ADD_DT","RMVL_DT","SPRTG_DOCN_LINK","STAT","CREATR","MODFR","CREATN_DT","CHG_DT","VRSN","ATTCHMT_FLG","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID","CMMTS" from AML_BLACKLIST_COUNTRY
/



CREATE OR REPLACE FORCE VIEW ODS.VW_AML_CIP_LETTER(AML_CIP_LTR_KEY, CIP_LTR_ID, LTR_YR, LTR_MO, LTR_TYPE, ACCT_OPEN_DT, LTR_SENT_DT, ACCT_CLOSD_DT, SHRHLDR_NM, MISSG_CIP_INFO, ADDL_CMMTS, CLOSG_AMT_REDMPN, CREATR_NM, STAT, ACCT_NBR, RSPN_DDLN_DT, EXPN_DT, CREATR, MODFR, CREATN_DT, CHG_DT, VRSN, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "AML_CIP_LTR_KEY","CIP_LTR_ID","LTR_YR","LTR_MO","LTR_TYPE","ACCT_OPEN_DT","LTR_SENT_DT","ACCT_CLOSD_DT","SHRHLDR_NM","MISSG_CIP_INFO","ADDL_CMMTS","CLOSG_AMT_REDMPN","CREATR_NM","STAT","ACCT_NBR","RSPN_DDLN_DT","EXPN_DT","CREATR","MODFR","CREATN_DT","CHG_DT","VRSN","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM AML_CIP_Letter
/



CREATE OR REPLACE FORCE VIEW ODS.VW_AML_DEALER_CONTRACTS(AML_DLR_CONTRCT_KEY, DLR_CONTRCT_ID, RQSTR, RQST_DT, LTR_TO_MKTG_FLG, DLR_NM, CONTCT_PERS, PHON_NBR, FAX_NBR, EMAIL_ADDR, AGRMT_TYPE_CMMTS, SGND_AGRMT_FLG, FEE_PMT_DETS, SELF_CLRING_DETS, CLRING_FIRM_NBR, DLR_OF_REC_FLG, DLR_OF_REC, PRIO, STAT, ASSGNE, INTRM_SENT_DT, CMMTS, ENTY_TYPE, EST_CPLTN_DT, FIRM_NM, CREATR, MODFR, CREATN_DT, CHG_DT, RQST_DT_AGNG, VRSN, TARC_AML_REVW, TARC_MKT_TMNG_REVW, TARC_OTHR_FNDG, RTRMT_SHR_CLS_INLSN_FLG, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID, REVW_RQST_DT, REVW_CPLTN_FLG, REVW_CPLTN_DT) AS 
select "AML_DLR_CONTRCT_KEY","DLR_CONTRCT_ID","RQSTR","RQST_DT","LTR_TO_MKTG_FLG","DLR_NM","CONTCT_PERS","PHON_NBR","FAX_NBR","EMAIL_ADDR","AGRMT_TYPE_CMMTS","SGND_AGRMT_FLG","FEE_PMT_DETS","SELF_CLRING_DETS","CLRING_FIRM_NBR","DLR_OF_REC_FLG","DLR_OF_REC","PRIO","STAT","ASSGNE","INTRM_SENT_DT","CMMTS","ENTY_TYPE","EST_CPLTN_DT","FIRM_NM","CREATR","MODFR","CREATN_DT","CHG_DT","RQST_DT_AGNG","VRSN","TARC_AML_REVW","TARC_MKT_TMNG_REVW","TARC_OTHR_FNDG","RTRMT_SHR_CLS_INLSN_FLG","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID","REVW_RQST_DT","REVW_CPLTN_FLG","REVW_CPLTN_DT" from aml_dealer_contracts
/



CREATE OR REPLACE FORCE VIEW ODS.VW_AML_FBAR_FILINGS(FBAR_FILNG_KEY, FUND_KEY, FBAR_FILNG_ID, LAST_FILNG_DT, YR, FUND_NM, CREATR, MODFR, CREATN_DT, CHG_DT, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID, ACTV_FUND_FLG, FUND_CLOS_DT, AMNDT_NBR, AMNDT_YR) AS 
select "FBAR_FILNG_KEY","FUND_KEY","FBAR_FILNG_ID","LAST_FILNG_DT","YR","FUND_NM","CREATR","MODFR","CREATN_DT","CHG_DT","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID","ACTV_FUND_FLG","FUND_CLOS_DT","AMNDT_NBR","AMNDT_YR" from aml_fbar_filings
/



CREATE OR REPLACE FORCE VIEW ODS.VW_AML_FINCEN(AML_FINCEN_KEY, FINCEN_ID, YR, QTR, FINCEN_LIST_PBSH_DT, REVWED_DT, FINCEN_SUBJ_CNT, ALRTS_REVW_CNT, FALSE_POS_CNT, UNCNRFMD_HITS_CNT, CONFRMD_HITS_CNT, TURN_ARND_TM, SPCL_FLG, CREATR, MODFR, CREATN_DT, CHG_DT, VRSN, ATTCHMT_FLG, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "AML_FINCEN_KEY","FINCEN_ID","YR","QTR","FINCEN_LIST_PBSH_DT","REVWED_DT","FINCEN_SUBJ_CNT","ALRTS_REVW_CNT","FALSE_POS_CNT","UNCNRFMD_HITS_CNT","CONFRMD_HITS_CNT","TURN_ARND_TM","SPCL_FLG","CREATR","MODFR","CREATN_DT","CHG_DT","VRSN","ATTCHMT_FLG","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM AML_FinCEN
/



CREATE OR REPLACE FORCE VIEW ODS.VW_AML_FOREIGN_CORR_BANKS(FORGN_CORRSP_BNK_KEY, FORGN_CORRSP_BNK_ID, ACCT_NBR, BNK_ADD_DT, BNK_RMVL_DT, STAT, BNK_NM, CREATR, CREATN_DT, MODFR, CHG_DT, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "FORGN_CORRSP_BNK_KEY","FORGN_CORRSP_BNK_ID","ACCT_NBR","BNK_ADD_DT","BNK_RMVL_DT","STAT","BNK_NM","CREATR","CREATN_DT","MODFR","CHG_DT","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM AML_Foreign_Corr_Banks
/



CREATE OR REPLACE FORCE VIEW ODS.VW_AML_POLICY_PROCEDURE(POL_PROCD_KEY, AML_POL_ID, POL_CD, HI_LVL_POL_NM, CHG_RECMN, MGMT_REVWER, EXEC_REVWER, STAT, APPRVL_DT, EFFTV_DT, AML_RELD_FLG, YR, CREATN_DT, CREATR, CHG_DT, MODFR, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "POL_PROCD_KEY","AML_POL_ID","POL_CD","HI_LVL_POL_NM","CHG_RECMN","MGMT_REVWER","EXEC_REVWER","STAT","APPRVL_DT","EFFTV_DT","AML_RELD_FLG","YR","CREATN_DT","CREATR","CHG_DT","MODFR","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM AML_Policy_Procedure
/



CREATE OR REPLACE FORCE VIEW ODS.VW_AML_QTRLY_DEALER_REVIEW(AML_QTRLY_DLR_REVW_KEY, RQST_DT, DLR_REVW_ID, PRIO, STAT, ASSGNE, DUE_DT, ATTCHMT_FLG, FIRM_NM, AGNG, DLR_ID, RPTG_QTR, RPTG_YR, REGLTY_VLTN_FLG, BRKR_FLG, AML_REVW, MKT_TMNG_REVW, OTHR_REGLTY_FNDG, RQSTR, CMMTS, CREATR, MODFR, CREATN_DT, CHG_DT, VRSN, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID, AML_RECERTFN_FLG, OTHR_RECERTFN_FLG, DLR_GRP_ID, CPLTN_DT) AS 
select "AML_QTRLY_DLR_REVW_KEY","RQST_DT","DLR_REVW_ID","PRIO","STAT","ASSGNE","DUE_DT","ATTCHMT_FLG","FIRM_NM","AGNG","DLR_ID","RPTG_QTR","RPTG_YR","REGLTY_VLTN_FLG","BRKR_FLG","AML_REVW","MKT_TMNG_REVW","OTHR_REGLTY_FNDG","RQSTR","CMMTS","CREATR","MODFR","CREATN_DT","CHG_DT","VRSN","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID","AML_RECERTFN_FLG","OTHR_RECERTFN_FLG","DLR_GRP_ID","CPLTN_DT" from aml_qtrly_dealer_review
/



CREATE OR REPLACE FORCE VIEW ODS.VW_AML_SAR(SAR_KEY, SAR_ID, ACCT_NBR, DOC_CNTL_NBR, ACT_CRCN_RSD_DT, SUSPICION_RSN, SAR_AMLCO_REVW_DT, FINCEN_FILED_FLG, SAR_FINCEN_FILNG_DT, SAR_FINCEN_FILNG_YR, SUSPECT_NM, CREATR, MODFR, CREATN_DT, CHG_DT, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID, SAR_TYPE, SAR_CAT, AMLCO_ACT_NTFN_DT, SAR_FILNG_DDLN_DT, SPRTG_DOC_LINK, CYBER_EVT_FLG) AS 
select "SAR_KEY","SAR_ID","ACCT_NBR","DOC_CNTL_NBR","ACT_CRCN_RSD_DT","SUSPICION_RSN","SAR_AMLCO_REVW_DT","FINCEN_FILED_FLG","SAR_FINCEN_FILNG_DT","SAR_FINCEN_FILNG_YR","SUSPECT_NM","CREATR","MODFR","CREATN_DT","CHG_DT","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID","SAR_TYPE","SAR_CAT","AMLCO_ACT_NTFN_DT","SAR_FILNG_DDLN_DT","SPRTG_DOC_LINK","CYBER_EVT_FLG" from aml_sar
/



CREATE OR REPLACE FORCE VIEW ODS.VW_AML_TRAINING_HISTORY(AML_TRNG_HIST_KEY, TRNG_HIST_ID, YR, ATTNDE_NM, CRSE_TITL, SESS_TYPE, CAT, PRNC_FLG, FCLYTR, SESS_LEN, NTES, TRNG_LINK, CERTFN_TYPE, TRNG_DT, EMPL_STAT, AML_TRNG_FLG, ATTCHMTS_FLG, ARCHVL_DT, TRNG_TITL, ORG_NM, PUBN_NM, ROLE, READ_FREQ, NEW_TRNG_RPT_FLG, CPLTN_FLG, DEPT, CEU, CREATR, MODFR, CREATN_DT, CHG_DT, CERTFC_TYPE, MBRS_STRT_DT, MBRS_EXPN_DT, ACAMS_RECERTFN_FLG, COST, VRSN, STRT_DT, RNL_DT, PMT_DT, CRSE_CMMTS, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "AML_TRNG_HIST_KEY","TRNG_HIST_ID","YR","ATTNDE_NM","CRSE_TITL","SESS_TYPE","CAT","PRNC_FLG","FCLYTR","SESS_LEN","NTES","TRNG_LINK","CERTFN_TYPE","TRNG_DT","EMPL_STAT","AML_TRNG_FLG","ATTCHMTS_FLG","ARCHVL_DT","TRNG_TITL","ORG_NM","PUBN_NM","ROLE","READ_FREQ","NEW_TRNG_RPT_FLG","CPLTN_FLG","DEPT","CEU","CREATR","MODFR","CREATN_DT","CHG_DT","CERTFC_TYPE","MBRS_STRT_DT","MBRS_EXPN_DT","ACAMS_RECERTFN_FLG","COST","VRSN","STRT_DT","RNL_DT","PMT_DT","CRSE_CMMTS","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM AML_Training_History
/



CREATE OR REPLACE FORCE VIEW ODS.VW_BUDGET(BUD_KEY, PROJ_KEY, CAT, BUD_AMT, APPRVD_AMT, TOT_INVCD_AMT, BUD_DT, BUD_YR, ALLOCN, ACCT_NBR, BUD_LINE_DESC, PRIR_YR_CARROVR, BUD_LINE_CMMT, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "BUD_KEY","PROJ_KEY","CAT","BUD_AMT","APPRVD_AMT","TOT_INVCD_AMT","BUD_DT","BUD_YR","ALLOCN","ACCT_NBR","BUD_LINE_DESC","PRIR_YR_CARROVR","BUD_LINE_CMMT","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM Budget
/



CREATE OR REPLACE FORCE VIEW ODS.VW_BUDGET_CATEGORY(BUD_CAT_KEY, BUD_CAT_ID, BUD_CAT_NM, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "BUD_CAT_KEY","BUD_CAT_ID","BUD_CAT_NM","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM Budget_Category
/



CREATE OR REPLACE FORCE VIEW ODS.VW_BUDGET_FACT(BUD_FACT_KEY, BUD_LINE_KEY, BUD_FACT_ID, BUD_YR, BUD_AMT, CREATR, MODFR, CREATN_DT, LAST_MODFD_DT, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "BUD_FACT_KEY","BUD_LINE_KEY","BUD_FACT_ID","BUD_YR","BUD_AMT","CREATR","MODFR","CREATN_DT","LAST_MODFD_DT","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM Budget_Fact
/



CREATE OR REPLACE FORCE VIEW ODS.VW_BUDGET_LINE(BUD_LINE_KEY, BUD_ID, VEND_KEY, PROJ_KEY, BUD_CAT_KEY, PROD_LINE_KEY, EXPNS_ACCT, EXPNS_ACCT_DESC, IT_BUD_CLSFCN, BUD_LINE_NM, BUD_LINE_STAT, CREATR, MODFR, CREATD_DT, LAST_MODFD_DT, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "BUD_LINE_KEY","BUD_ID","VEND_KEY","PROJ_KEY","BUD_CAT_KEY","PROD_LINE_KEY","EXPNS_ACCT","EXPNS_ACCT_DESC","IT_BUD_CLSFCN","BUD_LINE_NM","BUD_LINE_STAT","CREATR","MODFR","CREATD_DT","LAST_MODFD_DT","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM Budget_Line
/



CREATE OR REPLACE FORCE VIEW ODS.VW_CONTRACT_REVIEW(CONTRCT_REVW_KEY, VEND_KEY, BUD_LINE_KEY, BUD_CAT_KEY, PROD_LINE_KEY, CONTRCT_ID, CONTRCT_TYPE, CONTRCT_STRT_DT, CONTRCT_END_DT, PMT_FREQ, FREQ_AMT_EST, AUTO_RNL_FLG, NTFN_REQ_FLG, NTFN_PER, VEND_MGMT_PLN_TYPE, ACCT_MGR, ACCT_MGR_PHON, ACCT_MGR_EMAIL, NTFN_DDLN, CONTRCT_REVW_STRT, CONTRCT_STAT, RNL_PER, PROD_RSLR, LAST_OVST_REVW, OVST_FREQ, NEXT_OVST_SCHED_DT, FIXED_AMT, VARB_AMT, CONTRCT_OWNR, ROBECO_RPTG_FLG, VEND_MGMT_CLSFCN, INVC_MTHD, CREATR, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "CONTRCT_REVW_KEY","VEND_KEY","BUD_LINE_KEY","BUD_CAT_KEY","PROD_LINE_KEY","CONTRCT_ID","CONTRCT_TYPE","CONTRCT_STRT_DT","CONTRCT_END_DT","PMT_FREQ","FREQ_AMT_EST","AUTO_RNL_FLG","NTFN_REQ_FLG","NTFN_PER","VEND_MGMT_PLN_TYPE","ACCT_MGR","ACCT_MGR_PHON","ACCT_MGR_EMAIL","NTFN_DDLN","CONTRCT_REVW_STRT","CONTRCT_STAT","RNL_PER","PROD_RSLR","LAST_OVST_REVW","OVST_FREQ","NEXT_OVST_SCHED_DT","FIXED_AMT","VARB_AMT","CONTRCT_OWNR","ROBECO_RPTG_FLG","VEND_MGMT_CLSFCN","INVC_MTHD","CREATR","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM Contract_Review
/



CREATE OR REPLACE FORCE VIEW ODS.VW_DECISION_LIST(DECSN_LIST_KEY, PROJ_KEY, DECSN_ID, ASSGNE, STAT, RPTG_FLG, RSLN_DT, PROJ_IMPCT, LIST_CAT, PRBLTY, DUE_DT, PROJ_NM, PROJ_ID, LIST_TITL, LIST_DESC, LIST_CMMT, RSLN, LIST_CREATR, LIST_MODFR, LAST_MODFD_DT, DT_CREATD, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "DECSN_LIST_KEY","PROJ_KEY","DECSN_ID","ASSGNE","STAT","RPTG_FLG","RSLN_DT","PROJ_IMPCT","LIST_CAT","PRBLTY","DUE_DT","PROJ_NM","PROJ_ID","LIST_TITL","LIST_DESC","LIST_CMMT","RSLN","LIST_CREATR","LIST_MODFR","LAST_MODFD_DT","DT_CREATD","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM Decision_List
/



CREATE OR REPLACE FORCE VIEW ODS.VW_HSG_CALL_QUALITY_PROGRAM(CQ_PROG_KEY, CQ_PROG_ID, TITL, CALL_REVW_DT, CALL_REVWR_NM, CALL_TYPE, CALL_DRCTN, REP_NM, MNTR_TRNG_FLG, VCC_TXN_ID, CALL_DT, ACCT_NBR, CALLER_NM, REVWR_CMMTS, OTHR_CMMTS, SVC_LBRY_ADD_FLG, MNTR_NM, MGR_NM, OPTY_ADDD_VAL_FLG, OPTY_ADDD_VAL_MISSD_FLG, CALL_REVW_CMMT, DEPT, PRE_TOT_SCOR, PRE_TOT_SCOR_2, TOT_CALL_SCOR, GREETG_SCOR, PRES_BEHVR_SCOR, INFO_SCOR, CALL_QSTN_FOCUS_SCOR, HOLD_XFER_SCOR, CLOSG_SCOR, CREATR, MODFR, CREATN_DT, CHG_DT, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID, XTRA_CR_SCOR) AS 
select "CQ_PROG_KEY","CQ_PROG_ID","TITL","CALL_REVW_DT","CALL_REVWR_NM","CALL_TYPE","CALL_DRCTN","REP_NM","MNTR_TRNG_FLG","VCC_TXN_ID","CALL_DT","ACCT_NBR","CALLER_NM","REVWR_CMMTS","OTHR_CMMTS","SVC_LBRY_ADD_FLG","MNTR_NM","MGR_NM","OPTY_ADDD_VAL_FLG","OPTY_ADDD_VAL_MISSD_FLG","CALL_REVW_CMMT","DEPT","PRE_TOT_SCOR","PRE_TOT_SCOR_2","TOT_CALL_SCOR","GREETG_SCOR","PRES_BEHVR_SCOR","INFO_SCOR","CALL_QSTN_FOCUS_SCOR","HOLD_XFER_SCOR","CLOSG_SCOR","CREATR","MODFR","CREATN_DT","CHG_DT","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID","XTRA_CR_SCOR"
from  hsg_call_quality_program
/



CREATE OR REPLACE FORCE VIEW ODS.VW_HSG_CALL_QUALITY_QUESTION(CQ_QSTN_KEY, QSTN, QSTN_CAT, QSTN_COL_NM, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "CQ_QSTN_KEY","QSTN","QSTN_CAT","QSTN_COL_NM","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM HSG_Call_Quality_Question
/



CREATE OR REPLACE FORCE VIEW ODS.VW_HSG_CALL_QUALITY_RESULT(CQ_RSLT_KEY, CQ_PROG_KEY, CQ_QSTN_KEY, CQ_PROG_ID, QSTN_RSLT, QSTN_SCOR, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "CQ_RSLT_KEY","CQ_PROG_KEY","CQ_QSTN_KEY","CQ_PROG_ID","QSTN_RSLT","QSTN_SCOR","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM HSG_Call_Quality_Result
/



CREATE OR REPLACE FORCE VIEW ODS.VW_HSG_CHAT_QUALITY_QUESTION(CHAT_QUAL_QSTN_KEY, QSTN, QSTN_CAT, QSTN_COL_NM, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "CHAT_QUAL_QSTN_KEY","QSTN","QSTN_CAT","QSTN_COL_NM","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM HSG_Chat_Quality_Question
/



CREATE OR REPLACE FORCE VIEW ODS.VW_HSG_CHAT_QUALITY_RESULT(CHAT_QUAL_RSLT_KEY, CHAT_QUAL_QSTN_KEY, CHAT_QUAL_ID, TITL, DEPT, REVWR_CMMT, OTHR_CMMTS, MGR, CHAT_VAL, CHAT_SCOR, FNL_SCOR, REVW_DT, REVWR, REP, CHAT_DT, TXN_ID, CHAT_QUAL_REVW_CMMT, CREATR, MODFR, CREATN_DT, CHG_DT, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "CHAT_QUAL_RSLT_KEY","CHAT_QUAL_QSTN_KEY","CHAT_QUAL_ID","TITL","DEPT","REVWR_CMMT","OTHR_CMMTS","MGR","CHAT_VAL","CHAT_SCOR","FNL_SCOR","REVW_DT","REVWR","REP","CHAT_DT","TXN_ID","CHAT_QUAL_REVW_CMMT","CREATR","MODFR","CREATN_DT","CHG_DT","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM HSG_Chat_Quality_Result
/



CREATE OR REPLACE FORCE VIEW ODS.VW_HSG_CONTROL_DOCUMENT(CNTL_DOC_KEY, CNTL_DOC_ID, DLR_ID, REVW_YR, PROG_YR, DOC_TYPE, RQST_DT, FIRM_RSPN, RECPT_DT, REVW_STAT, OVST_STAT, PRES_DT, CPLTN_DT, AUDT_REVW_PER, CMMTS, GEN_CMMTS, GRP_ID, PRIM_AUDT_RPT_RECVD, SECY_AUDT_RPT_RECVD, ADDL_DOCS_RECVD_FLG, ASSGNE, AUDT_STRT_DT, AUDT_END_DT, AUDTR_OPN, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "CNTL_DOC_KEY","CNTL_DOC_ID","DLR_ID","REVW_YR","PROG_YR","DOC_TYPE","RQST_DT","FIRM_RSPN","RECPT_DT","REVW_STAT","OVST_STAT","PRES_DT","CPLTN_DT","AUDT_REVW_PER","CMMTS","GEN_CMMTS","GRP_ID","PRIM_AUDT_RPT_RECVD","SECY_AUDT_RPT_RECVD","ADDL_DOCS_RECVD_FLG","ASSGNE","AUDT_STRT_DT","AUDT_END_DT","AUDTR_OPN","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM HSG_Control_Document
/



CREATE OR REPLACE FORCE VIEW ODS.VW_HSG_CONTROL_DOCUMENTS(HSG_CNTL_DOC_KEY, HSG_CNTL_DOC_ID, FIRM_NM, REVW_YR, DOC_TYPE, INTRL_CNTL_DOC_LINK, RQST_DT, ASSGNE, FIRM_RSPN, RECVD_DT, REVW_STAT, OVST_STAT, PRES_DT, CPLTN_DT, AUDT_REVW_PER, CMMTS, GEN_CMMTS, MRQC_DESC, MRQC_ADDL_INFO, RGP_DESC, RGP_ADDL_INFO, TPO_MGMT, TPO_ADDL_INFO, COE_MGMT_DESC, COE_TST, COE_FNDG, COE_ADDL_INFO, ISP_MGMT_DESC, ISP_TST, ISP_FNDG, ISP_ADDL_INFO, AML_N_PTF_MGMT_DESC, AML_N_PTF_TST, AML_N_PTF_FNDG, AML_N_PTF_ADDL_INFO, DOCR_N_RK_MGMT_DESC, DOCR_N_RK_TST, DOCR_N_RK_FNDG, DOCR_N_RK_ADDL_INFO, SMSM_MGMT_DESC, TPFNF_MGMT_DESC, SMSM_TST, SMSM_FNDG, SMSM_ADDL_INFO, TPFNF_TST, TPFNF_FNDG, TPFNF_ADDL_INFO, CSR_MGMT_DESC, CSR_TST, CSR_FNDG, CSR_ADDL_INFO, LMS_MGMT_DESC, LMS_TST, LMS_FNDG, LMS_ADDL_INFO, SHRHLDR_COMM_MGMT_DESC, SHRHLDR_COMM_TST, SHRHLDR_COMM_FNDG, SHRHLDR_COMM_ADDL_INFO, SABIP_MGMT_DESC, SABIP_TST, SABIP_FNDG, SABIP_ADDL_INFO, FEE_CALCS_MGMT_DESC, FEE_CALCS_TST, FEE_CALCS_FNDG, FEE_CALCS_ADDL_INFO, INFO_TECHN_MGMT_DESC, INFO_TECHN_TST, INFO_TECHN_FNDG, INFO_TECHN_ADDL_INFO, BCP_DR_MGMT_DESC, BCP_DR_TST, BCP_DR_FNDG, BCP_DR_ADDL_INFO, BSKY_RPTG_MGMT_DESC, BSKY_RPTG_TST, BSKY_RPTG_FNDG, BSKY_RPTG_ADDL_INFO, MGMT_RPTG_FLWUP_RQST_DT, MGMT_RPTG_FLWUP_RSPN_DT, RGP_FLWUP_RQST_DT, RGP_FLWUP_RSPN_DT, TPO_FLWUP_RQST_DT, TPO_FLWUP_RSPN_DT, COE_FLWUP_RQST_DT, COE_FLWUP_RSPN_DT, ISP_FLWUP_RQST_DT, ISP_FLWUP_RSPN_DT, AML_N_PTF_FLWUP_RQST_DT, AML_N_PTF_FLWUP_RSPN_DT, DOCR_N_RK_FLWUP_RQST_DT, DOCR_N_RK_FLWUP_RSPN_DT, CSR_FLWUP_RQST_DT, CSR_FLWUP_RSPN_DT, LMS_FLWUP_RQST_DT, LMS_FLWUP_RSPN_DT, SHRHLDR_COMMS_FLWUP_RQST_DT, SHRHLDR_COMMS_FLWUP_RSPN_DT, SABIP_FLWUP_RQST_DT, SABIP_FLWUP_RSPN_DT, FEE_CALCS_FLWUP_RQST_DT, FEE_CALCS_FLWUP_RSPN_DT, INFO_TECHN_FLWUP_RQST_DT, INFO_TECHN_FLWUP_RSPN_DT, BCP_DR_FLWUP_RQST_DT, BCP_DR_FLWUP_RSPN_DT, BSKY_RPTG_FLWUP_RQST_DT, BSKY_RPTG_FLWUP_RSPN_DT, SMSM_FLWUP_RQST_DT, SMSM_FLWUP_RSPN_DT, TPFNF_FLWUP_RQST_DT, TPFNF_FLWUP_RSPN_DT, CREATN_DT, CHG_DT, CREATR, MODFR, AUDTR_OPN, DLR_ID, DLR_GRP_ID, AUDT_STRT_DT, AUDT_END_DT, PROG_YR, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID, PRIM_AUDT_RPT_NM, SECY_AUDT_RPT_NM, ADDL_DOC_RECPT_FLG) AS 
select "HSG_CNTL_DOC_KEY","HSG_CNTL_DOC_ID","FIRM_NM","REVW_YR","DOC_TYPE","INTRL_CNTL_DOC_LINK","RQST_DT","ASSGNE","FIRM_RSPN","RECVD_DT","REVW_STAT","OVST_STAT","PRES_DT","CPLTN_DT","AUDT_REVW_PER","CMMTS","GEN_CMMTS","MRQC_DESC","MRQC_ADDL_INFO","RGP_DESC","RGP_ADDL_INFO","TPO_MGMT","TPO_ADDL_INFO","COE_MGMT_DESC","COE_TST","COE_FNDG","COE_ADDL_INFO","ISP_MGMT_DESC","ISP_TST","ISP_FNDG","ISP_ADDL_INFO","AML_N_PTF_MGMT_DESC","AML_N_PTF_TST","AML_N_PTF_FNDG","AML_N_PTF_ADDL_INFO","DOCR_N_RK_MGMT_DESC","DOCR_N_RK_TST","DOCR_N_RK_FNDG","DOCR_N_RK_ADDL_INFO","SMSM_MGMT_DESC","TPFNF_MGMT_DESC","SMSM_TST","SMSM_FNDG","SMSM_ADDL_INFO","TPFNF_TST","TPFNF_FNDG","TPFNF_ADDL_INFO","CSR_MGMT_DESC","CSR_TST","CSR_FNDG","CSR_ADDL_INFO","LMS_MGMT_DESC","LMS_TST","LMS_FNDG","LMS_ADDL_INFO","SHRHLDR_COMM_MGMT_DESC","SHRHLDR_COMM_TST","SHRHLDR_COMM_FNDG","SHRHLDR_COMM_ADDL_INFO","SABIP_MGMT_DESC","SABIP_TST","SABIP_FNDG","SABIP_ADDL_INFO","FEE_CALCS_MGMT_DESC","FEE_CALCS_TST","FEE_CALCS_FNDG","FEE_CALCS_ADDL_INFO","INFO_TECHN_MGMT_DESC","INFO_TECHN_TST","INFO_TECHN_FNDG","INFO_TECHN_ADDL_INFO","BCP_DR_MGMT_DESC","BCP_DR_TST","BCP_DR_FNDG","BCP_DR_ADDL_INFO","BSKY_RPTG_MGMT_DESC","BSKY_RPTG_TST","BSKY_RPTG_FNDG","BSKY_RPTG_ADDL_INFO","MGMT_RPTG_FLWUP_RQST_DT","MGMT_RPTG_FLWUP_RSPN_DT","RGP_FLWUP_RQST_DT","RGP_FLWUP_RSPN_DT","TPO_FLWUP_RQST_DT","TPO_FLWUP_RSPN_DT","COE_FLWUP_RQST_DT","COE_FLWUP_RSPN_DT","ISP_FLWUP_RQST_DT","ISP_FLWUP_RSPN_DT","AML_N_PTF_FLWUP_RQST_DT","AML_N_PTF_FLWUP_RSPN_DT","DOCR_N_RK_FLWUP_RQST_DT","DOCR_N_RK_FLWUP_RSPN_DT","CSR_FLWUP_RQST_DT","CSR_FLWUP_RSPN_DT","LMS_FLWUP_RQST_DT","LMS_FLWUP_RSPN_DT","SHRHLDR_COMMS_FLWUP_RQST_DT","SHRHLDR_COMMS_FLWUP_RSPN_DT","SABIP_FLWUP_RQST_DT","SABIP_FLWUP_RSPN_DT","FEE_CALCS_FLWUP_RQST_DT","FEE_CALCS_FLWUP_RSPN_DT","INFO_TECHN_FLWUP_RQST_DT","INFO_TECHN_FLWUP_RSPN_DT","BCP_DR_FLWUP_RQST_DT","BCP_DR_FLWUP_RSPN_DT","BSKY_RPTG_FLWUP_RQST_DT","BSKY_RPTG_FLWUP_RSPN_DT","SMSM_FLWUP_RQST_DT","SMSM_FLWUP_RSPN_DT","TPFNF_FLWUP_RQST_DT","TPFNF_FLWUP_RSPN_DT","CREATN_DT","CHG_DT","CREATR","MODFR","AUDTR_OPN","DLR_ID","DLR_GRP_ID","AUDT_STRT_DT","AUDT_END_DT","PROG_YR","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID","PRIM_AUDT_RPT_NM","SECY_AUDT_RPT_NM","ADDL_DOC_RECPT_FLG" from hsg_control_documents
/



CREATE OR REPLACE FORCE VIEW ODS.VW_HSG_CONTROL_DOC_FINDINGS(CNTL_DOC_FNDG_KEY, CNTL_DOC_LINE_KEY, CNTL_DOC_FNDG_ID, SUB_SCTN_NM, AUDT_REVW_STRT_PER, AUDT_REVW_END_PER, CNTL_NBR, FNDG_DESC, EXCPN_NTED, MGMT_RSPN, HBR_CMMTS, FIRM_NM, CONTXT_MTGN_CNTL, CREATR, MODFR, CREATN_DT, CHG_DT, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID, PAGE_NBR) AS 
select "CNTL_DOC_FNDG_KEY","CNTL_DOC_LINE_KEY","CNTL_DOC_FNDG_ID","SUB_SCTN_NM","AUDT_REVW_STRT_PER","AUDT_REVW_END_PER","CNTL_NBR","FNDG_DESC","EXCPN_NTED","MGMT_RSPN","HBR_CMMTS","FIRM_NM","CONTXT_MTGN_CNTL","CREATR","MODFR","CREATN_DT","CHG_DT","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID","PAGE_NBR" from hsg_control_doc_findings
/



CREATE OR REPLACE FORCE VIEW ODS.VW_HSG_CONTROL_DOC_LINE(CNTL_DOC_LINE_KEY, CNTL_DOC_KEY, CNTL_AREA, MGMT_DESC_FLG, TST_FLG, FNDG_FLG, INIT_REVW_CMMTS, PAGE_NBRS, OVST_CMTE_CMMTS, ADDL_INFO_RQST_FLG, FLWUP_RQST_DT, FLWUP_RSPN_DT, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "CNTL_DOC_LINE_KEY","CNTL_DOC_KEY","CNTL_AREA","MGMT_DESC_FLG","TST_FLG","FNDG_FLG","INIT_REVW_CMMTS","PAGE_NBRS","OVST_CMTE_CMMTS","ADDL_INFO_RQST_FLG","FLWUP_RQST_DT","FLWUP_RSPN_DT","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM HSG_Control_Doc_Line
/



CREATE OR REPLACE FORCE VIEW ODS.VW_HSG_DEALER_FEE_ANALYSIS(DLR_FEE_ANLYS_KEY, DLR_FEE_ANLYS_ID, LIST_TITL, INVC_DT, MTHLY_12B1_FEES, YTD_12B1_FEES, MTHLY_SUBTA_FEES, YTD_SUBTA_FEES, MTHLY_MIN_FEES, YTD_MIN_FEES, MTHLY_PER_ACCT_INST_FEES, YTD_PER_ACCT_INST_FEES, MTHLY_PLFM_FEES, YTD_PLFM_FEES, YTD_BUD_12B1_FEES, YTD_BUD_SUBTA_FEES, YTD_BUD_MIN_FEES, YTD_BUD_PER_ACCT_INST_FEES, YTD_BUD_PLFM_FEES, BUD_VAR_12B1_FEES, SUBTA_BUD_VAR, MIN_FEE_BUD_VAR, PER_ACCT_INST_BUD_VAR, PLFM_BUD_VAR, CREATR, MODFR, CREATN_DT, CHG_DT, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "DLR_FEE_ANLYS_KEY","DLR_FEE_ANLYS_ID","LIST_TITL","INVC_DT","MTHLY_12B1_FEES","YTD_12B1_FEES","MTHLY_SUBTA_FEES","YTD_SUBTA_FEES","MTHLY_MIN_FEES","YTD_MIN_FEES","MTHLY_PER_ACCT_INST_FEES","YTD_PER_ACCT_INST_FEES","MTHLY_PLFM_FEES","YTD_PLFM_FEES","YTD_BUD_12B1_FEES","YTD_BUD_SUBTA_FEES","YTD_BUD_MIN_FEES","YTD_BUD_PER_ACCT_INST_FEES","YTD_BUD_PLFM_FEES","BUD_VAR_12B1_FEES","SUBTA_BUD_VAR","MIN_FEE_BUD_VAR","PER_ACCT_INST_BUD_VAR","PLFM_BUD_VAR","CREATR","MODFR","CREATN_DT","CHG_DT","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM HSG_Dealer_Fee_Analysis
/



CREATE OR REPLACE FORCE VIEW ODS.VW_HSG_PROJECT_DOCUMENT(HSG_PROJ_DOC_KEY, PROJ_DOC_ID, PROJ_TITL, PROJ_MGR, PROJ_NM, DOC_TYPE, AGND_ITEM_FLG, OBJV, CHG_RQST, PROJ_DLVBL, MS, RSRC_RESPY, RSKS, EST_HRS, ACTL_HRS, PROJ_DOCN_APPRVR, PROJ_DOCN_PREV_SUBM, PROJ_ISSS, BUS_CHG_CNTL, BUS_DRVR, PROG_VAL, PRES_DT, PROJ_SCP_APPRVL_DT, TRGT_CPLTN_DT, PROJ_FOLDR_LOCN, PROJ_STAT, CMMTS, PROJ_FREQ, RSRC_MGR, LSN_LRND, PROJ_CHG_APPRVL_DT, CLOSOUT_APPRVL_DT, LIFE_CYC_TYPE, INITN_HRS_EST, PLNG_HRS_EST, EXCTN_HRS_EST, MNTRG_HRS_EST, CLOSG_HRS_EST, TOT_HRS_EST, PROJ_MTG_FREQ, CLOSOUT_MTG_FLG, PROJ_DOC_ARCHV_FLG, STAT_MTG_FLG, CHG_RQST_1_EST, CHG_RQST_2_EST, CHG_RQST_3_EST, CHG_RQST_4_EST, CHG_RQST_5_EST, CHG_RQST_6_EST, CHG_RQST_7_EST, CHG_RQST_8_EST, CHG_RQST_9_EST, RVSD_TOT_HRS_EST, RVSD_TRGT_CPLTN_DT_1, ACTL_CPLTN_DT, YR_QTR, CHG_RQST_1_RSN, CHG_RQST_2_RSN, CHG_RQST_3_RSN, CHG_RQST_4_RSN, CHG_RQST_5_RSN, CHG_RQST_6_RSN, CHG_RQST_7_RSN, CHG_RQST_8_RSN, CHG_RQST_9_RSN, RVSD_TRGT_CPLTN_DT_2, RVSD_TRGT_CPLTN_DT_3, RVSD_TRGT_CPLTN_DT_4, RVSD_TRGT_CPLTN_DT_5, RVSD_TRGT_CPLTN_DT_6, RVSD_TRGT_CPLTN_DT_7, RVSD_TRGT_CPLTN_DT_8, RVSD_TRGT_CPLTN_DT_9, COST_IMPCT_IND, COST_IMPCT, COST_CHG_DESC, COST_IMPCT_DESC, COST_IMPCT_ORIG_EST, CREATR, MODFR, CREATN_DT, CHG_DT, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "HSG_PROJ_DOC_KEY","PROJ_DOC_ID","PROJ_TITL","PROJ_MGR","PROJ_NM","DOC_TYPE","AGND_ITEM_FLG","OBJV","CHG_RQST","PROJ_DLVBL","MS","RSRC_RESPY","RSKS","EST_HRS","ACTL_HRS","PROJ_DOCN_APPRVR","PROJ_DOCN_PREV_SUBM","PROJ_ISSS","BUS_CHG_CNTL","BUS_DRVR","PROG_VAL","PRES_DT","PROJ_SCP_APPRVL_DT","TRGT_CPLTN_DT","PROJ_FOLDR_LOCN","PROJ_STAT","CMMTS","PROJ_FREQ","RSRC_MGR","LSN_LRND","PROJ_CHG_APPRVL_DT","CLOSOUT_APPRVL_DT","LIFE_CYC_TYPE","INITN_HRS_EST","PLNG_HRS_EST","EXCTN_HRS_EST","MNTRG_HRS_EST","CLOSG_HRS_EST","TOT_HRS_EST","PROJ_MTG_FREQ","CLOSOUT_MTG_FLG","PROJ_DOC_ARCHV_FLG","STAT_MTG_FLG","CHG_RQST_1_EST","CHG_RQST_2_EST","CHG_RQST_3_EST","CHG_RQST_4_EST","CHG_RQST_5_EST","CHG_RQST_6_EST","CHG_RQST_7_EST","CHG_RQST_8_EST","CHG_RQST_9_EST","RVSD_TOT_HRS_EST","RVSD_TRGT_CPLTN_DT_1","ACTL_CPLTN_DT","YR_QTR","CHG_RQST_1_RSN","CHG_RQST_2_RSN","CHG_RQST_3_RSN","CHG_RQST_4_RSN","CHG_RQST_5_RSN","CHG_RQST_6_RSN","CHG_RQST_7_RSN","CHG_RQST_8_RSN","CHG_RQST_9_RSN","RVSD_TRGT_CPLTN_DT_2","RVSD_TRGT_CPLTN_DT_3","RVSD_TRGT_CPLTN_DT_4","RVSD_TRGT_CPLTN_DT_5","RVSD_TRGT_CPLTN_DT_6","RVSD_TRGT_CPLTN_DT_7","RVSD_TRGT_CPLTN_DT_8","RVSD_TRGT_CPLTN_DT_9","COST_IMPCT_IND","COST_IMPCT","COST_CHG_DESC","COST_IMPCT_DESC","COST_IMPCT_ORIG_EST","CREATR","MODFR","CREATN_DT","CHG_DT","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM HSG_Project_Document
/



CREATE OR REPLACE FORCE VIEW ODS.VW_HSG_WORKFLOW_TASK(WKFL_TASK_KEY, HSG_PROJ_DOC_KEY, WKFL_TASK_ID, WKFL_TITL, ASSGNE, WKFL_STAT, PRIO, STRT_DT, DDT, CPLTN_FLG, CONTNT_LINK, OUTC, TASK_GRP_ID, WKFL_DESC, WKFL_NM, EXT_PARTCP, EXT_PARTCP_RSN, CREATR, MODFR, CREATN_DT, CHG_DT, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "WKFL_TASK_KEY","HSG_PROJ_DOC_KEY","WKFL_TASK_ID","WKFL_TITL","ASSGNE","WKFL_STAT","PRIO","STRT_DT","DDT","CPLTN_FLG","CONTNT_LINK","OUTC","TASK_GRP_ID","WKFL_DESC","WKFL_NM","EXT_PARTCP","EXT_PARTCP_RSN","CREATR","MODFR","CREATN_DT","CHG_DT","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM HSG_Workflow_Task
/



CREATE OR REPLACE FORCE VIEW ODS.VW_INVOICE(INVC_KEY, VEND_KEY, BUD_LINE_KEY, PROD_LINE_KEY, INVC_ID, INVC_NBR, INVC_DT, EXPNS_ACCT, EXPNS_ACCT_DESC, PURCH_ORD, WKFL_CPLTN_DT, INVC_YR, WKFL_YR, TOT_INVC_AMT, BUD_ITEM_AMT, INVC_NOTE, CREATN_DT, LAST_CHG_DT, CREATR, MODFR, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "INVC_KEY","VEND_KEY","BUD_LINE_KEY","PROD_LINE_KEY","INVC_ID","INVC_NBR","INVC_DT","EXPNS_ACCT","EXPNS_ACCT_DESC","PURCH_ORD","WKFL_CPLTN_DT","INVC_YR","WKFL_YR","TOT_INVC_AMT","BUD_ITEM_AMT","INVC_NOTE","CREATN_DT","LAST_CHG_DT","CREATR","MODFR","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM Invoice
/



CREATE OR REPLACE FORCE VIEW ODS.VW_IPM_FIRM_PROFILES(IPM_FIRM_PROF_KEY, FIRM_STAT, PRIM_COVG_PERS, SECY_COVG_PERS, STRG, FIRM_NM, FIRM_CONTCT, FIRM_CMMT, DOC_LINK, CREATR, MODFR, CREATN_DT, LAST_UPDT_DT, NEXT_STEPS, FIRM_PROF_LIST_ID, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "IPM_FIRM_PROF_KEY","FIRM_STAT","PRIM_COVG_PERS","SECY_COVG_PERS","STRG","FIRM_NM","FIRM_CONTCT","FIRM_CMMT","DOC_LINK","CREATR","MODFR","CREATN_DT","LAST_UPDT_DT","NEXT_STEPS","FIRM_PROF_LIST_ID","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM IPM_Firm_Profiles
/



CREATE OR REPLACE FORCE VIEW ODS.VW_IPM_MANAGER_ANALYSIS(IPM_MGR_ANLYS_KEY, FIRM_NM, ANLYS_DT, ANLYS_OBJV, ANALYSER, ANLYS_TITL, ANLYS_LINK, ANLYS_RSLT, CREATR, MODFR, CREATN_DT, LAST_UPDT_DT, MGR_ANLYS_LIST_ID, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "IPM_MGR_ANLYS_KEY","FIRM_NM","ANLYS_DT","ANLYS_OBJV","ANALYSER","ANLYS_TITL","ANLYS_LINK","ANLYS_RSLT","CREATR","MODFR","CREATN_DT","LAST_UPDT_DT","MGR_ANLYS_LIST_ID","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM IPM_Manager_Analysis
/



CREATE OR REPLACE FORCE VIEW ODS.VW_IPM_MANAGER_UPDATES(IPM_MGR_UPDT_KEY, FIRM_NM, UPDT_TYPE, UPDT_DT, ACTN_STEP, UPDT_TITL, CREATR, MODFR, CREATN_DT, LAST_UPDT_DT, MGR_UPDT_LIST_ID, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "IPM_MGR_UPDT_KEY","FIRM_NM","UPDT_TYPE","UPDT_DT","ACTN_STEP","UPDT_TITL","CREATR","MODFR","CREATN_DT","LAST_UPDT_DT","MGR_UPDT_LIST_ID","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM IPM_Manager_Updates
/



CREATE OR REPLACE FORCE VIEW ODS.VW_IPM_MEETINGS(IPM_MTG_KEY, MTG_DT, FOCUS_AREA, HBR_ATTNDE, CURR_PROS, MTG_TYPE, MTG_SUM, FIRM_NM, YR, QTR, FIRM_ATTNDE, SUM_WRTR, PRE_MTG_NOTES, MTG_NOTES, FIRM_PROF, CMTE_MTG_TYPE, CREATR, MODFR, CREATN_DT, LAST_UPDT_DT, MTG_LIST_ID, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "IPM_MTG_KEY","MTG_DT","FOCUS_AREA","HBR_ATTNDE","CURR_PROS","MTG_TYPE","MTG_SUM","FIRM_NM","YR","QTR","FIRM_ATTNDE","SUM_WRTR","PRE_MTG_NOTES","MTG_NOTES","FIRM_PROF","CMTE_MTG_TYPE","CREATR","MODFR","CREATN_DT","LAST_UPDT_DT","MTG_LIST_ID","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM IPM_Meetings
/



CREATE OR REPLACE FORCE VIEW ODS.VW_ISSUE_LIST(ISS_LIST_KEY, ISS_ID, ISS_DESC, ACCT_NBR, AGING, ASSGNE, BMG_ASSGNE, CONTNT_TYPE, DLR_ID, DLR_ISS_TYPE, HSG_DEPT, DUE_DT, FUND_NBR, ISS_ORIG, OVST_RPTB_FLG, SYS_TYPE, PRIO, PROJ_NM, PROJ_LOCN, ISS_REPORTER, RSRH_CMMT, RSLN, AWD_SEND_FLG, TCKT_NBR, ISS_TITL, RQST_TYPE, FAN_USR_ID, VEND_IMPCT, FAN_VRSN, BRWSR_NM, CREATR, CREATN_DT, MODFR, LAST_MODFD_DT, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "ISS_LIST_KEY","ISS_ID","ISS_DESC","ACCT_NBR","AGING","ASSGNE","BMG_ASSGNE","CONTNT_TYPE","DLR_ID","DLR_ISS_TYPE","HSG_DEPT","DUE_DT","FUND_NBR","ISS_ORIG","OVST_RPTB_FLG","SYS_TYPE","PRIO","PROJ_NM","PROJ_LOCN","ISS_REPORTER","RSRH_CMMT","RSLN","AWD_SEND_FLG","TCKT_NBR","ISS_TITL","RQST_TYPE","FAN_USR_ID","VEND_IMPCT","FAN_VRSN","BRWSR_NM","CREATR","CREATN_DT","MODFR","LAST_MODFD_DT","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM Issue_List
/



CREATE OR REPLACE FORCE VIEW ODS.VW_MARKET_TIMING(MKT_TMNG_KEY, MKT_TMNG_ID, MAILG_DT, SYS_NM, ACCT_NBR, FUND_DESC, DLR_ID, SHRHLDR_PLN, WARN_BAN_TYPE, RND_TRIP_CNT, MKT_TMNG_INTN, SECY_DLR_ID, BAN_STAT, BAN_EXPN_DT, CREATR, MODFR, CREATN_DT, CHG_DT, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "MKT_TMNG_KEY","MKT_TMNG_ID","MAILG_DT","SYS_NM","ACCT_NBR","FUND_DESC","DLR_ID","SHRHLDR_PLN","WARN_BAN_TYPE","RND_TRIP_CNT","MKT_TMNG_INTN","SECY_DLR_ID","BAN_STAT","BAN_EXPN_DT","CREATR","MODFR","CREATN_DT","CHG_DT","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM Market_Timing
/



CREATE OR REPLACE FORCE VIEW ODS.VW_PMO_TASKS(PMO_TASKS_KEY, PROJ_KEY, TASK_IDX, TASK_NM, PLN_STRT_DT, PLN_FINISH_DT, STRT_DT, FINISH_DT, CPLTN_PCT, MS_RPTG_FLG, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "PMO_TASKS_KEY","PROJ_KEY","TASK_IDX","TASK_NM","PLN_STRT_DT","PLN_FINISH_DT","STRT_DT","FINISH_DT","CPLTN_PCT","MS_RPTG_FLG","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM PMO_Tasks
/



CREATE OR REPLACE FORCE VIEW ODS.VW_PRODUCT_LINE(PROD_LINE_KEY, PROD_CD, PROD_NM, PROD_VEND_NM, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "PROD_LINE_KEY","PROD_CD","PROD_NM","PROD_VEND_NM","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM Product_Line
/



CREATE OR REPLACE FORCE VIEW ODS.VW_PROJECTS(PROJ_KEY, PROJ_ID, PROJ_MGR, PROJ_SPSR, PROJ_TCHL_LEAD, PROJ_DRVR, IT_DEPT, BUS_UT, CRIT_TOT, PHASE, CAT, PROJ_NM, BUS_CASE, RSRC_USGE, DUR, EXPCTD_PROJ_INITN, BUDGE_SCOR, BUS_PARTCN_SCOR, RISK_SCOR, RSRC_USGE_SCOR, PROJ_DUR_SCOR, TEAM_CMPXTY_SCOR, TECHN_SCOR, NEW_HDWR_BUD, NEW_SFTW_BUD, CNSLTT_BUD, MNGD_SVC_BUD, BUD_TOT, PMO_APPRVL_STAT, PMO_DECSN_DT, PMO_CMMTS, OAL_PROJ_STAT, SCHED_STAT, BUD_STAT, PROJ_STAT_CMMTS, CLOSR_STAT, CLOSR_CPLTN_SUM, CLOSR_CRIT_SUCCS_RTNG, FNL_BUD, FNL_RSRC_USGE, FNL_DUR, SPSR_CLOSR_APPRVL_DT, PMO_CLOSR_APPRVL_DT, CLOSR_APPRVL_CMMTS, PROJ_DESC, PROJ_ACTV_TITL, PROJ_DOCN_LINK, PROJ_LOG_LINK, PROJ_SCHED_LINK, REC_CREATR, USR_LAST_MODFD, DT_CREATD, DT_LAST_MODFD, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
select "PROJ_KEY","PROJ_ID","PROJ_MGR","PROJ_SPSR","PROJ_TCHL_LEAD","PROJ_DRVR","IT_DEPT","BUS_UT","CRIT_TOT","PHASE","CAT","PROJ_NM","BUS_CASE","RSRC_USGE","DUR","EXPCTD_PROJ_INITN","BUDGE_SCOR","BUS_PARTCN_SCOR","RISK_SCOR","RSRC_USGE_SCOR","PROJ_DUR_SCOR","TEAM_CMPXTY_SCOR","TECHN_SCOR","NEW_HDWR_BUD","NEW_SFTW_BUD","CNSLTT_BUD","MNGD_SVC_BUD","BUD_TOT","PMO_APPRVL_STAT","PMO_DECSN_DT","PMO_CMMTS","OAL_PROJ_STAT","SCHED_STAT","BUD_STAT","PROJ_STAT_CMMTS","CLOSR_STAT","CLOSR_CPLTN_SUM","CLOSR_CRIT_SUCCS_RTNG","FNL_BUD","FNL_RSRC_USGE","FNL_DUR","SPSR_CLOSR_APPRVL_DT","PMO_CLOSR_APPRVL_DT","CLOSR_APPRVL_CMMTS","PROJ_DESC","PROJ_ACTV_TITL","PROJ_DOCN_LINK","PROJ_LOG_LINK","PROJ_SCHED_LINK","REC_CREATR","USR_LAST_MODFD","DT_CREATD","DT_LAST_MODFD","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID"
from projects
/



CREATE OR REPLACE FORCE VIEW ODS.VW_SPL_HSG_CHANGE_CONTROL(CHG_CNTL_KEY, BUS_AREA, CHG_CNTL_ID, BUS_DRVR, PROG_NM, PROJ_NM, HSG_DEPT, CHG_CNTL_TITL, CHG_BUS_RSN, CHG_DESC, CHG_STAT, CHG_CMMT, PRES_DT, APPRVL_DT, TRGT_DT, TM_EST, RSRC_EST, QTR_PER, VLDN_CPLT_FLG, CHG_CNTL_WKFL_NBR, PROJ_MGR, CREATN_DT, MODFY_DT, CREATR, MODFR, AML_FLG, YE_RELD_FLG, FLD_CPLTN_STAT, DOC_ATTCHMT_STAT, SIGNOFF_STAT, TMLY_CPLTN_STAT, CHG_CNTL_UPDT_STAT, QA_CMMT_1, QA_CMMT_2, QA_CMMT_3, QA_CMMT_4, QA_CMMT_5, QA_ITEM_FLG, VRSN, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID, HI_LVL_POL_FLG) AS 
select "CHG_CNTL_KEY","BUS_AREA","CHG_CNTL_ID","BUS_DRVR","PROG_NM","PROJ_NM","HSG_DEPT","CHG_CNTL_TITL","CHG_BUS_RSN","CHG_DESC","CHG_STAT","CHG_CMMT","PRES_DT","APPRVL_DT","TRGT_DT","TM_EST","RSRC_EST","QTR_PER","VLDN_CPLT_FLG","CHG_CNTL_WKFL_NBR","PROJ_MGR","CREATN_DT","MODFY_DT","CREATR","MODFR","AML_FLG","YE_RELD_FLG","FLD_CPLTN_STAT","DOC_ATTCHMT_STAT","SIGNOFF_STAT","TMLY_CPLTN_STAT","CHG_CNTL_UPDT_STAT","QA_CMMT_1","QA_CMMT_2","QA_CMMT_3","QA_CMMT_4","QA_CMMT_5","QA_ITEM_FLG","VRSN","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID","HI_LVL_POL_FLG" from SPL_HSG_CHANGE_CONTROL
/



CREATE OR REPLACE FORCE VIEW ODS.VW_SPL_HSG_COMPLAINTS(CMPLNT_KEY, CMPLNT_ID, CMPLNT_TITL, STAT, ASSGNE, REC_TYPE, CAT_VAL, RECVD_DT, ORIG_DEPT, CMPLNT_TYPE, FDBK_REP, ACCT_NBR, FUND_NBR, ISS_DESC, SOLN_DESC, ADDL_INFO, ACCT_COMPRMED_FLG, TCKT_ID, PRNC_REVW_DT, WRTTN_CMPLNT_ID, LGL_STAT, FINRA_FILNG_FLG, FINRA_FILNG_DT, AGING, BKUP_DOCN_LINK, CEO_ESCL_FLG, CEO_ESCL_DT, CCO_ESCL_FLG, CCO_ESCL_DT, CMO_ESCL_FLG, CMO_ESCL_DT, ADDR_LINE, CITY, ST, ZIP_CD, PUSH_NTFN_VAL, PUSH_NTFN_ID, PUSH_NTFN_EMAIL, FINRA_RPTG_PER, PRNC_REVWER, BMG_ISS_LINK, HSG_RSLN_DT, LIST_HDDN_VRSN, LIST_VRSN, URL_PATH, BUS_AREA, BUS_DRVR, PROG, PROJ_NM, HSG_DEPT, CHG_BUS_RSN, CHG_DESC, CMMT, PRES_DT, APPRVL_DT, TRGT_DT, LINK_1, LINK_2, TM_EST, RSRC_EST, VLDN_CPLTN, QTR, CHG_CNTL_WKFL, PROJ_MGR, CREATR, MODFR, DT_CREATD, DT_MODFD, CMPLNT_YR, CMPLNT_MO, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
select "CMPLNT_KEY","CMPLNT_ID","CMPLNT_TITL","STAT","ASSGNE","REC_TYPE","CAT_VAL","RECVD_DT","ORIG_DEPT","CMPLNT_TYPE","FDBK_REP","ACCT_NBR","FUND_NBR","ISS_DESC","SOLN_DESC","ADDL_INFO","ACCT_COMPRMED_FLG","TCKT_ID","PRNC_REVW_DT","WRTTN_CMPLNT_ID","LGL_STAT","FINRA_FILNG_FLG","FINRA_FILNG_DT","AGING","BKUP_DOCN_LINK","CEO_ESCL_FLG","CEO_ESCL_DT","CCO_ESCL_FLG","CCO_ESCL_DT","CMO_ESCL_FLG","CMO_ESCL_DT","ADDR_LINE","CITY","ST","ZIP_CD","PUSH_NTFN_VAL","PUSH_NTFN_ID","PUSH_NTFN_EMAIL","FINRA_RPTG_PER","PRNC_REVWER","BMG_ISS_LINK","HSG_RSLN_DT","LIST_HDDN_VRSN","LIST_VRSN","URL_PATH","BUS_AREA","BUS_DRVR","PROG","PROJ_NM","HSG_DEPT","CHG_BUS_RSN","CHG_DESC","CMMT","PRES_DT","APPRVL_DT","TRGT_DT","LINK_1","LINK_2","TM_EST","RSRC_EST","VLDN_CPLTN","QTR","CHG_CNTL_WKFL","PROJ_MGR","CREATR","MODFR","DT_CREATD","DT_MODFD","CMPLNT_YR","CMPLNT_MO","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" from  SPL_HSG_COMPLAINTS
/



CREATE OR REPLACE FORCE VIEW ODS.VW_SPL_HSG_DAILY_TASKS_MAINT(ID, COMMENTS, COMPLETED_BY, DAILY_TASK, DAILY_TASK_DEPARTMENT, TASK_DATE, PASS_FAIL, TASK_ASSIGNED_TO, VERIFIED_BY, DCS_CALLS_OFFERED, TASK_EDIT, TASK_TITLE, TASK_LINKTITLENOMENU, TASK_LINKTITLE, DAILY_TASK_TASK, DAILY_TASK_PRIORITY, DAILY_TASK_DEADLINE, DAILY_TASK_SOURCE, DAILY_TASK_BCP_TASK, CREATED_BY, MODIFIED_BY, MODIFIED, CREATED, DCS_CALLS_ANSWERED, DCS_AVERAGE_SPEED_OF_ANSWER, DCS_SERVICE_LEVEL, DCS_MTD_SLA, DCS_CALLS_ABANDONED, CONTENT_TYPE, TASK_VERSION, ATTACHMENTS, TYPE, ITEM_CHILD_COUNT, FOLDER_CHILD_COUNT, CURR_ROW_FLG, PURGED_OR_DEL, ROW_STRT_DTTM, ROW_UPDT_DTTM, REASON_FOR_FAIL, AREA_OF_RESPONSIBILITY, DAILY_TASKS_ID, CMPLTN_TIME) AS 
select "ID","COMMENTS","COMPLETED_BY","DAILY_TASK","DAILY_TASK_DEPARTMENT","TASK_DATE","PASS_FAIL","TASK_ASSIGNED_TO","VERIFIED_BY","DCS_CALLS_OFFERED","TASK_EDIT","TASK_TITLE","TASK_LINKTITLENOMENU","TASK_LINKTITLE","DAILY_TASK_TASK","DAILY_TASK_PRIORITY","DAILY_TASK_DEADLINE","DAILY_TASK_SOURCE","DAILY_TASK_BCP_TASK","CREATED_BY","MODIFIED_BY","MODIFIED","CREATED","DCS_CALLS_ANSWERED","DCS_AVERAGE_SPEED_OF_ANSWER","DCS_SERVICE_LEVEL","DCS_MTD_SLA","DCS_CALLS_ABANDONED","CONTENT_TYPE","TASK_VERSION","ATTACHMENTS","TYPE","ITEM_CHILD_COUNT","FOLDER_CHILD_COUNT","CURR_ROW_FLG","PURGED_OR_DEL","ROW_STRT_DTTM","ROW_UPDT_DTTM","REASON_FOR_FAIL","AREA_OF_RESPONSIBILITY","DAILY_TASKS_ID","CMPLTN_TIME" from SPL_HSG_DAILY_TASKS_MAINT
/



CREATE OR REPLACE FORCE VIEW ODS.VW_SPL_HSG_ISSUE_LIST(ISS_LIST_KEY, ISS_ID, ISS_DESC, ACCT_NBR, AGNG, ASSGNE, BMG_ASSGNE, CONTNT_TYPE, DLR_ID, DLR_ISS_TYPE, HSG_DEPT, DDT, FUND_NBR, ISS_ORIG, OVST_RPTB_FLG, SYS_TYPE, PRIO, PROJ_NM, PROJ_LOCN, ISS_RPTER, RSRH_CMMT, RSLN, AWD_SEND_FLG, TCKT_NBR, ISS_TITL, RQST_TYPE, FAN_USR_ID, VEND_IMPCT, FAN_VRSN, BRWSR_NM, PROG_NM, BUS_DRVR, ISS_STAT, AML_RECERTFN, FINCEN_REVW, ORIG_TRGT_DDT, RVSD_TRGT_DDT, TRGT_DDT_RVSR, CREATR, CREATN_DT, MODFR, LAST_MODFD_DT, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID, DLR_GRP_ID, DLR_ID_LIST, ISS_CREATN_DT, ISS_CLOSOUT_DT) AS 
select "ISS_LIST_KEY","ISS_ID","ISS_DESC","ACCT_NBR","AGNG","ASSGNE","BMG_ASSGNE","CONTNT_TYPE","DLR_ID","DLR_ISS_TYPE","HSG_DEPT","DDT","FUND_NBR","ISS_ORIG","OVST_RPTB_FLG","SYS_TYPE","PRIO","PROJ_NM","PROJ_LOCN","ISS_RPTER","RSRH_CMMT","RSLN","AWD_SEND_FLG","TCKT_NBR","ISS_TITL","RQST_TYPE","FAN_USR_ID","VEND_IMPCT","FAN_VRSN","BRWSR_NM","PROG_NM","BUS_DRVR","ISS_STAT","AML_RECERTFN","FINCEN_REVW","ORIG_TRGT_DDT","RVSD_TRGT_DDT","TRGT_DDT_RVSR","CREATR","CREATN_DT","MODFR","LAST_MODFD_DT","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID","DLR_GRP_ID","DLR_ID_LIST","ISS_CREATN_DT","ISS_CLOSOUT_DT" from spl_hsg_issue_list
/



CREATE OR REPLACE FORCE VIEW ODS.VW_VENDOR(VEND_KEY, VEND_ID, VEND_NM, VEND_STAT, CREATR, MODFR, CREATD_DT, LAST_MODFD_DT, CURR_ROW_FLG, ROW_STRT_DTTM, ROW_STOP_DTTM, ETL_LOAD_CYC_KEY, SRC_SYS_ID) AS 
SELECT "VEND_KEY","VEND_ID","VEND_NM","VEND_STAT","CREATR","MODFR","CREATD_DT","LAST_MODFD_DT","CURR_ROW_FLG","ROW_STRT_DTTM","ROW_STOP_DTTM","ETL_LOAD_CYC_KEY","SRC_SYS_ID" FROM Vendor
/




 

